import type { Disclosure } from './types';

/**
 * Offline fallback data — used only when GET /api/feed is unreachable.
 * Mirrors the web prototype's SAMPLE and the Supabase seed shape so the app
 * renders meaningfully with no network. Verdicts are derived by labelOf(),
 * never hard-coded here.
 */
export const SAMPLE: Omit<Disclosure, 'label'>[] = [
  { id: 1, actor: 'Renaissance Technologies', kind: '13F Fund', initials: 'RT', source: '13F-HR', side: 'BUY', ticker: 'NVDA', company: 'NVIDIA Corp.', amount: '$15K–$50K', amountMid: 32500, transactionDate: 'Jun 17, 2026', filingDate: 'Jun 25, 2026', businessStatus: 'pass', business: 'Hardware, chips, AI infrastructure', impurePct: 0, debtRatio: 3.2, screened: true, reasoning: 'Permissible technology business with no impure income and low debt.' },
  { id: 2, actor: 'Public Official Filing', kind: 'Congress', initials: 'PO', source: 'House PTR', side: 'BUY', ticker: 'AVGO', company: 'Broadcom Inc.', amount: '$50K–$100K', amountMid: 75000, transactionDate: 'Jun 15, 2026', filingDate: 'Jun 24, 2026', businessStatus: 'watch', business: 'Semiconductors & infrastructure software', impurePct: 1.4, debtRatio: 19, screened: true, reasoning: 'Core business permissible; a small slice of revenue is non-operating income.' },
  { id: 3, actor: 'Global Value Fund', kind: '13F Fund', initials: 'GV', source: '13F-HR', side: 'SELL', ticker: 'JPM', company: 'JPMorgan Chase & Co.', amount: '$50K–$100K', amountMid: 75000, transactionDate: 'Jun 11, 2026', filingDate: 'Jun 23, 2026', businessStatus: 'fail', business: 'Conventional interest-based banking', impurePct: 71, debtRatio: 0, screened: true, reasoning: 'Excluded at the business-activity level: conventional banking and interest income are core to the model.' },
  { id: 4, actor: 'Public Official Filing', kind: 'Congress', initials: 'PO', source: 'House PTR', side: 'SELL', ticker: 'XOM', company: 'Exxon Mobil Corp.', amount: '$15K–$50K', amountMid: 32500, transactionDate: 'Jun 02, 2026', filingDate: 'Jun 17, 2026', businessStatus: 'pass', business: 'Energy production', impurePct: 0, debtRatio: 52, screened: true, reasoning: 'Permissible energy business, no impure income. Debt is above the advisory reference — advisory only, so Purify-at-sale.' },
  { id: 5, actor: 'Northstar Quant Partners', kind: '13F Fund', initials: 'NQ', source: '13F-HR', side: 'BUY', ticker: 'MSFT', company: 'Microsoft Corp.', amount: '$100K–$250K', amountMid: 175000, transactionDate: 'Jun 10, 2026', filingDate: 'Jun 20, 2026', businessStatus: 'pass', business: 'Software & cloud infrastructure', impurePct: 0, debtRatio: 11, screened: true, reasoning: 'Permissible software business with no impure income and modest debt.' },
  { id: 6, actor: 'Corporate Insider Filing', kind: 'Insider', initials: 'IN', source: 'Form 4', side: 'SELL', ticker: 'TSLA', company: 'Tesla, Inc.', amount: '$250K–$500K', amountMid: 375000, transactionDate: 'Jun 09, 2026', filingDate: 'Jun 12, 2026', businessStatus: 'pass', business: 'Electric vehicles & energy', impurePct: 2.1, debtRatio: 8, screened: true, reasoning: 'Permissible business; a small non-operating income slice keeps it at Purify-at-sale.' },
  { id: 7, actor: 'Northstar Quant Partners', kind: '13F Fund', initials: 'NQ', source: '13F-HR', side: 'BUY', ticker: 'NVDA', company: 'NVIDIA Corp.', amount: '$50K–$100K', amountMid: 75000, transactionDate: 'Jun 08, 2026', filingDate: 'Jun 19, 2026', businessStatus: 'pass', business: 'Hardware, chips, AI infrastructure', impurePct: 0, debtRatio: 3.2, screened: true, reasoning: 'Permissible technology business with no impure income and low debt.' },
  { id: 8, actor: 'Public Official Filing', kind: 'Congress', initials: 'PO', source: 'Senate PTR', side: 'BUY', ticker: 'UBS', company: 'UBS Group AG', amount: '$1K–$15K', amountMid: 8000, transactionDate: 'Jun 08, 2026', filingDate: 'Jun 18, 2026', screened: false, business: 'Unscreened', businessStatus: 'watch', impurePct: 0, debtRatio: 0, reasoning: 'No screening data available for this ticker — flagged for manual review.' },
];
