// GET  /api/notifications              -> { items:[...], unread:N } for the authed user
// POST /api/notifications { id }        -> mark one read
// POST /api/notifications { all:true }  -> mark all read
//
// The in-app Alerts inbox (Following tab). Rows are generated by the poll loop when a followed
// portfolio files a new disclosure. Auth-gated; tolerates the table being absent (returns an
// empty inbox) so the app works before the migration is run.
import { parseBody } from "./_lib/http.js";
import { supabase } from "./_lib/supabase.js";
import { requireAuth } from "./_lib/auth.js";
import { unreadCount } from "./_lib/notify.js";

export default async function handler(req, res) {
  const user = requireAuth(req);
  if (!user) return res.status(401).json({ error: "Unauthorized" });
  const body = req.method === "POST" ? parseBody(req) : null;
  if (req.method === "POST" && !body) return res.status(400).json({ error: "Invalid request body" });
  if (req.method === "POST" && !body.all && body.id == null) {
    return res.status(400).json({ error: "id or all:true required" });
  }
  const userId = user.username;

  try {
    const db = supabase();
    if (req.method === "GET") {
      const { data, error } = await db
        .from("notifications")
        .select("id,disclosure_id,portfolio,title,created_at,read_at")
        .eq("user_id", userId)
        .order("created_at", { ascending: false })
        .limit(100);
      if (error) throw error;
      const items = data || [];
      return res.status(200).json({ items, unread: unreadCount(items) });
    }

    if (req.method === "POST") {
      const nowIso = new Date().toISOString();
      let q = db.from("notifications").update({ read_at: nowIso }).eq("user_id", userId).is("read_at", null);
      if (!body.all) {
        q = q.eq("id", body.id);
      }
      const { error } = await q;
      if (error) throw error;
      return res.status(200).json({ ok: true });
    }

    return res.status(405).json({ error: "Method not allowed" });
  } catch (e) {
    if (req.method === "GET") return res.status(200).json({ items: [], unread: 0 });
    return res.status(500).json({ error: e.message });
  }
}
